### ISSUE TITLE
ローマ字ではなく英語でアクション名を記述する

### ISSUE THREAD

**Issue by norotime** [yousuke-shiraishi/demoday4-1#10]
https://github.com/yousuke-shiraishi/demoday4-1/blob/f88fd550886ef5383acaefaf654c14713137eed4/app/controllers/members_controller.rb#L22

tokurokuではなく、createで良いのではないでしょうか？

**Comment by yousuke-shiraishi** [comment]
@norotime 一日命名で悩んだのですが登録方法の分岐なのでdispatch(振り分け)にしました。
ご意見ありがとうございます。

**Comment by norotime** [comment]
@yousuke-shiraishi はい。基本は英語にしてください。ローマ字は、完全NGでお願いします。

**Comment by yousuke-shiraishi** [comment]
@norotime dispatchは予約語だったらしくエラーが出ました。dispatchingに修正いたしました。
