### ISSUE TITLE
動作していないコードはmasterにコミットしない

### ISSUE THREAD

**Issue by norotime** [yousuke-shiraishi/demoday4-1#4]
https://github.com/yousuke-shiraishi/demoday4-1/blob/5f2ae2634471a8c8896b5b2a1f0ce1c1a05e36b1/app/controllers/gmaps_controller.rb#L39

@yousuke-shiraishi 本番反映されてしまいます。顧客向けシステムだとすると完全にアウトな書き方です。masterには、動くコードのみを記述してください。

**Comment by yousuke-shiraishi** [comment]
コメントアウトしているコードが本番反映されるというのは初めて知りました。かなり勉強不足です。

**Comment by norotime** [comment]
@yousuke-shiraishi コメントアウトしていても、ソースコードとしてサーバにはデプロイされますよね？という意味でございます。

**Comment by norotime** [comment]
「新築の住宅の壁に落書きをする」のと同じ行為です。
