### ISSUE TITLE
改行等で見やすくコーディング規約を遵守する

### ISSUE THREAD

**Issue by norotime** [yousuke-shiraishi/demoday4-1#5]
https://github.com/yousuke-shiraishi/demoday4-1/blob/5f2ae2634471a8c8896b5b2a1f0ce1c1a05e36b1/app/controllers/gmaps_controller.rb#L83

@yousuke-shiraishi コーディング規約は、遵守してください。神経質なくらいがちょうど良いです。面接時に相当細かく見られます。（私だったら、コードだけで落とします。）
http://www.ruby.or.jp/ja/tech/development/ruby/050_coding_rule.html

**Comment by yousuke-shiraishi** [comment]
ありがとうございます。コード規約じっくり読んでみようと思います。

**Comment by norotime** [comment]
@yousuke-shiraishi エンジニアにとってのコードは、ライターにとっての日本語と同じです。
