### ISSUE TITLE
使用しないjsonレンダリングは削除する

### ISSUE THREAD

**Issue by norotime** [yousuke-shiraishi/demoday4-1#6]
https://github.com/yousuke-shiraishi/demoday4-1/blob/5f2ae2634471a8c8896b5b2a1f0ce1c1a05e36b1/app/controllers/gmaps_controller.rb#L47

@yousuke-shiraishi レンダリングで使用していますか？していない場合は削除しましょう。
使わないコードは記述しないのが王道のやり方です。

**Comment by yousuke-shiraishi** [comment]
削除しました。自動生成されるコードはどこかで使われているのでは？という意識もあり放っていたのですが
言われてみればたしかに必要のないコードですね。そこの見極めがまだ良く解っていないのです。

**Comment by norotime** [comment]
@yousuke-shiraishi しっかりと見極めてください。思考停止は、エンジニアにとっては、 *死* を意味します。
