### ISSUE TITLE
READMEに仕様や環境構成、導入手順を明記する

### ISSUE THREAD

**Issue by norotime** [yousuke-shiraishi/demoday4-1#7]
@yousuke-shiraishi 
https://github.com/yousuke-shiraishi/demoday4-1/blob/master/README.md
READMEファイルの書き方をGoogleで検索してみると良いです。

**Comment by norotime** [comment]
https://deeeet.com/writing/2014/07/31/readme/

英語は無理に使わなくても良いですー。

**Comment by yousuke-shiraishi** [comment]
インストールのさせ方なんてさっぱりわからないのですがどうすれば良いですか。依存関係もgemを大量に使っていて使っていないgemもあるのでブラッシュアップが必要なのですが。

**Comment by norotime** [comment]
@yousuke-shiraishi 手順だけ記載するのはどうですか？

**Comment by yousuke-shiraishi** [comment]
必要になるgemはこれから精査したいと思っております。gemlockを見ればバージョンもわかりますし。ただAWS関連で入れたgemと便利サイトで見て入れた。ツール等は取捨選択が必要だと思っています。後はyarnやbootstrapに関する注意事項を載せようと思っております。とりあえずredmeファイルの書き方について調べてからですが。

**Comment by norotime** [comment]
@yousuke-shiraishi そうですね！まずは、小さく、試しに描いてみましょ！

**Comment by norotime** [comment]
@yousuke-shiraishi 完了していたら、クローズにしましょう！

**Comment by yousuke-shiraishi** [comment]
@norotime クローズするのを忘れておりました。クローズ致します。
ありがとうございます。
