### ISSUE TITLE
コーディング規約：The Ruby Style Guide を遵守しましょう。

### ISSUE THREAD

**Issue by norotime** [yousuke-shiraishi/demoday4-1#8]
この書き方はNGです。

https://github.com/yousuke-shiraishi/demoday4-1/blob/f88fd550886ef5383acaefaf654c14713137eed4/app/controllers/gmaps_controller.rb#L9

*コーディング規約：The Ruby Style Guide を遵守しましょう。*
https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md

**Comment by norotime** [comment]
@yousuke-shiraishi ここも。
https://github.com/yousuke-shiraishi/demoday4-1/blob/f88fd550886ef5383acaefaf654c14713137eed4/app/controllers/gmaps_controller.rb#L19

他にもあるので全部修正してください。

**Comment by yousuke-shiraishi** [comment]
@norotime
よくは分からないのですがコーディング規約を見て空のメソッドはOKという記述を見てこちらの方にしたのですがどうなのでしょうか。




 本文が空のメソッドはこのルールの例外です。
# 良い例
def no_op; end
という一文を見たのですが。

**Comment by yousuke-shiraishi** [comment]
@norotime 一応before actionが効いているので空ではないという判断でしょうか。
