### ISSUE TITLE
拡張子がHTMLのみであればformat指定の記述は省く

### ISSUE THREAD

**Issue by norotime** [yousuke-shiraishi/demoday4-1#9]
https://github.com/yousuke-shiraishi/demoday4-1/blob/f88fd550886ef5383acaefaf654c14713137eed4/app/controllers/gmaps_controller.rb#L28

@yousuke-shiraishi 複数拡張子に対応させる場合のみこのオプション指定をお願いします。

**Comment by yousuke-shiraishi** [comment]
@norotime 確かにソニックガーデンの方に指摘されたところでもありました。修正いたします。
